language: ruby
rvm:
  - 2.2
addons:
  apt_packages:
    - libmagic-dev
services:
  - postgresql
before_install:
  - npm install -g bower
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - git config --global user.email 'tester@example.com'
  - git config --global user.name 'A Tester'
script:
  - phantomjs -v
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake bower:install
  - bundle exec rake spec
  - bundle exec rake cucumber
