version: '{build}'
skip_tags: true
# AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
#skip_commits:
#  message: /\[ci skip\]/
clone_depth: 10
services:
  - postgresql
environment:
  matrix:
    # there's a problem loading nokogiri 1.5.11 in Ruby 2.x on Windows
    #- ruby_version: '21'
    #- ruby_version: '21-x64'
    #- ruby_version: '200'
    #- ruby_version: '200-x64'
    - ruby_version: '22'
install:
  # Suppress warnings about ansicon
  - cinst ansicon
  # Take default Ruby out of path
  - SET PATH=%PATH:C:\Ruby193\bin;=%
  # Add Ruby to path from build matrix
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - ruby --version
  - gem --version
  - cinst PhantomJS -y
  - SET PATH=%path%;C:\tools\PhantomJS\
  - phantomjs -v
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - npm -v
  - npm install -g bower
  - bundle --deployment
# build_script:
#   - bundle exec rake build
build: off
test_script:
  - createdb appveyor_ci_test
  - cp config/database.yml.appveyor config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake bower:install
  - bundle exec rake assets:precompile RAILS_ENV=test
  - bundle exec rake spec
  - bundle exec rake cucumber
artifacts:
  - path: pkg\*.gem
