json.id jurisdiction.id
json.name jurisdiction.name
json.legislative_body jurisdiction.legislative_body
json.government_type jurisdiction.government_type
json.executive_review jurisdiction.executive_review
